### PR TITLE
GUI, executable with pyinstaller, and interactive cli

### PR DESCRIPTION
**Pull request by tonywied17**
### Main Changes/Additions
- Updated `requirements.txt` and `README.md`.
- Added a GUI option and a more Interactive CLI.
- Added a standalone executable with PyInstaller to launch the GUI easily.
- Added `bulk_txt` property to the `config.json` for bulk import processing.

### GUI screen grab video
https://github.com/user-attachments/assets/1edc1f6b-0d1b-4e13-9c32-2723151c5b1b

### Interactive CLI Mode
image

### CODE REVIEW

**Comment by tonywied17** [comment]
oh also i love you

**Comment by bbrown430** [comment]
@tonywied17 This is crazy dude, well done! Let me know when you've made your final commit and I'll look it over and merge it. This is going to be such a huge help and really improve the user experience.

**Comment by tonywied17** [comment]
Haha yeah this actually spun off from a side project I was working on that used CustomTkinter for a user interface. I realized it could be a great addition to your plex poster scraper for I didn't have to keep launching terminals lol. This script has been a lifesaver for me as kometa or whatever didn't like to apply my poster sets.

Most of your original code is intact since the UI primarily calls those functions in threaded processes. The main changes I made were updating `plex_setup` to handle exceptions more gracefully in the UI, so it doesn’t close unexpectedly and allows users to input the config. I also added predefined variables for `title` and `year` in `scrape_mediux` to handle cases where they weren’t defined—this was causing errors, possibly with deleted or missing poster sets. Now, it skips over those and processes the valid sets without issue.

It should be good to merge—I’ve been using it frequently, and it seems stable. You might want to double-check the `README`, though; I updated it but didn’t thoroughly review it afterward.

**Comment by tonywied17** [comment]
one last thing: needed right click context menu for clipboard actions (didn't realize that wasn't enabled by default) for those who don't use ctrl-c, ctrl-v

**Comment by bbrown430** [comment]
@tonywied17 sorry, I got busy and forgot about this, but just merged! Awesome work and thank you again for all your hard work on this.

**Pull request merged**
